config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students 

  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many:student
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :students, :subjects
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :groups
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
  @student = Student.new(student_params)
  @student.save
  redirect_to @student
  end

  private
  def student_params
    params.require(:student).permit(:name, :email, :mark, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <<body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mark</th>
  </tr>
 
 <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.email%></td>
      <td><%= student.mark%></td>
      <td><%= student.subject%></td>
      <td><%= link_to 'Show', student_path(student) %></td>
    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<%= form_with scope: :student,url: students_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

      <p>
    <%= form.label :subject %><br>
    <%= form.text_field :subject %>
  </p>

  <p>
    <%= form.label :mark %><br>
    <%= form.text_field :mark %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Mark</strong>
  <%= @student.mark %>
</p>